# Generated by Django 5.2 on 2025-04-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldtripSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'formulario de registro de un usuario a un fieldtrip',
                'verbose_name_plural': 'Formularios de registro de usuarios en Fieldtrips',
            },
        ),
        migrations.CreateModel(
            name='HealthDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log de la información de salud',
                'verbose_name_plural': 'Log de la Información de Salud',
            },
        ),
        migrations.CreateModel(
            name='HealthGral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.IntegerField(choices=[(1, 'Ha presentado'), (2, 'Presenta')], verbose_name='Indique el tipo de ítem')),
                ('item', models.CharField(max_length=255, verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'ítem de salud general',
                'verbose_name_plural': 'Ítems de Salud General',
            },
        ),
        migrations.CreateModel(
            name='HealthGralStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='¿Aplica esta condición para usted?')),
            ],
            options={
                'verbose_name': 'estatus de ítem de salud general',
                'verbose_name_plural': 'Estatus de Ítems de Salud General',
            },
        ),
        migrations.CreateModel(
            name='HealthSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'ítem de salud específico',
                'verbose_name_plural': 'Ítems de Salud Específicos',
            },
        ),
        migrations.CreateModel(
            name='HealthSpecificValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Ingrese su respuesta')),
            ],
            options={
                'verbose_name': 'información de ítem de salud específico',
                'verbose_name_plural': 'Información de Ítems de Salud Específicos',
            },
        ),
    ]
