# Generated by Django 5.2 on 2025-04-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtripsignup',
            name='checklist_status',
            field=models.ManyToManyField(blank=True, related_name='fieldtrip_signups', to='main.checkliststatus', verbose_name='Estado del checklist'),
        ),
        migrations.AddField(
            model_name='fieldtripsignup',
            name='fieldtrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtrip', verbose_name='Salida a terreno'),
        ),
    ]
