# Generated by Django 5.2 on 2025-04-14 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkliststatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.educationalinstitution', verbose_name='Institución educacional'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profesor a cargo'),
        ),
        migrations.AddField(
            model_name='checkliststatus',
            name='fieldtrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtrip'),
        ),
        migrations.AddField(
            model_name='fieldtripattendee',
            name='fieldtrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtrip'),
        ),
        migrations.AddField(
            model_name='fieldtripattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'institution'), name='unique_course_name_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='checkliststatus',
            constraint=models.UniqueConstraint(fields=('user', 'fieldtrip', 'item'), name='unique_checklist_status'),
        ),
        migrations.AddConstraint(
            model_name='fieldtripattendee',
            constraint=models.UniqueConstraint(fields=('user', 'fieldtrip', 'timestamp'), name='unique_fieldtrip_attendee'),
        ),
    ]
