# Generated by Django 5.2 on 2025-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_fieldtrip_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='SvyjkFKQxBYo3C7JxTwifr', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
