# Generated by Django 5.2 on 2025-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_fieldtrip_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrip',
            name='active',
            field=models.BooleanField(default=False, verbose_name='¿Está activa la salida a campo?'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='TyBsrkG5cJVch2Va63xtDn', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
