# Generated by Django 5.2 on 2025-04-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_fieldtripattendee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='aQEjiJ5or47bCSAqEZaBYK', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
