# Generated by Django 5.2 on 2025-11-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInstitutionEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'equipamiento de institución educacional',
                'verbose_name_plural': 'Equipamiento de Instituciones Educacionales',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'equipamiento',
                'verbose_name_plural': 'Equipamiento',
            },
        ),
        migrations.CreateModel(
            name='EquipmentInUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'equipamiento en uso',
                'verbose_name_plural': 'Equipamiento en Uso',
            },
        ),
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'equipamiento de usuario',
                'verbose_name_plural': 'Equipamiento de Usuarios',
            },
        ),
    ]
