# Generated by Django 5.2 on 2025-11-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalinstitutionequipment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.educationalinstitution', verbose_name='Institución educacional'),
        ),
        migrations.AddField(
            model_name='educationalinstitutionequipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Tipo de equipamiento'),
        ),
        migrations.AddField(
            model_name='equipmentinuse',
            name='fieldtrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtrip'),
        ),
        migrations.AddField(
            model_name='equipmentinuse',
            name='item_in_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.educationalinstitutionequipment', verbose_name='Stock de equipamiento'),
        ),
        migrations.AddField(
            model_name='userequipment',
            name='fieldtrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtrip'),
        ),
        migrations.AddField(
            model_name='userequipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Tipo de equipamiento'),
        ),
    ]
