# Generated by Django 5.2 on 2025-04-14 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userequipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddConstraint(
            model_name='educationalinstitutionequipment',
            constraint=models.UniqueConstraint(fields=('institution', 'type'), name='unique_institution_equipment'),
        ),
        migrations.AddConstraint(
            model_name='equipmentinuse',
            constraint=models.UniqueConstraint(fields=('fieldtrip', 'item_in_stock'), name='unique_fieldtrip_equipment_in_use'),
        ),
        migrations.AddConstraint(
            model_name='userequipment',
            constraint=models.UniqueConstraint(fields=('user', 'fieldtrip', 'type'), name='unique_user_fieldtrip_equipment'),
        ),
    ]
