# Generated by Django 5.2 on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_initial'),
        ('main', '0004_fieldtripattendee_is_auxiliar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad solicitada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('fieldtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtrip', verbose_name='Salida a campo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Tipo de equipamiento')),
            ],
            options={
                'verbose_name': 'solicitud de equipamiento',
                'verbose_name_plural': 'Solicitudes de Equipamiento',
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentrequest',
            constraint=models.UniqueConstraint(fields=('fieldtrip', 'type'), name='unique_fieldtrip_equipment_request'),
        ),
    ]
