# Generated by Django 5.2 on 2026-05-14 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinuse',
            name='item_in_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.educationalinstitutionequipment', verbose_name='Cantidad de equipamiento'),
        ),
        migrations.AlterField(
            model_name='equipmentinuse',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad a usar'),
        ),
    ]
