# Generated by Django 5.2 on 2025-11-12 20:50

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, unique=True, verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'ítem de checklist',
                'verbose_name_plural': 'Checklist',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código del curso')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la institución educacional')),
            ],
            options={
                'verbose_name': 'institución educacional',
                'verbose_name_plural': 'Instituciones Educacionales',
            },
        ),
        migrations.CreateModel(
            name='Fieldtrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la salida a campo')),
                ('invitation_code', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de término')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector al que se irá')),
                ('cached_checklist', models.JSONField(blank=True, default=list, verbose_name='Checklist guardado al momento de la creación')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'salida a campo',
                'verbose_name_plural': 'Salidas a Campo',
            },
        ),
        migrations.CreateModel(
            name='FieldtripAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_complete', models.BooleanField(blank=True, default=False, verbose_name='Status de registro en salida')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'asistente a salida',
                'verbose_name_plural': 'Asistentes a Salida a Campo',
            },
        ),
        migrations.CreateModel(
            name='ChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_item', models.CharField(blank=True, max_length=200, verbose_name='Valor original del ítem')),
                ('status', models.BooleanField(verbose_name='Estatus')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.checklist', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'estatus de ítem en checklist',
                'verbose_name_plural': 'Estatus de ítem en Checklist',
            },
        ),
    ]
