# Generated by Django 5.2 on 2025-04-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='4uuBC7RuEyai7kDVt4kZUo', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
