# Generated by Django 5.2 on 2026-03-12 19:08

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_fieldtrip_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtripattendee',
            name='is_auxiliar',
            field=models.BooleanField(default=False, verbose_name='Es auxiliar en esta salida a campo'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
