# Generated by Django 5.2 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fieldtripattendee_is_auxiliar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtripattendee',
            name='is_group_leader',
            field=models.BooleanField(default=False, verbose_name='Es líder de grupo en esta salida a campo'),
        ),
    ]