# Generated by Django 5.2 on 2026-05-14 23:01

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fieldtripattendee_is_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
