# Generated by Django 5.2 on 2025-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fieldtrip_active_alter_fieldtrip_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='cached_checklist',
            field=models.JSONField(blank=True, default=list, verbose_name='Checklist guardado al momento de la creación'),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='G7dGMwyZy9BnfsW5vxLu4j', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
