# Generated by Django 5.2 on 2025-04-14 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_fieldtrip_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldtripattendee',
            options={'verbose_name': 'asistente a salida', 'verbose_name_plural': 'Asistentes a Salida a Campo'},
        ),
        migrations.RemoveConstraint(
            model_name='fieldtripattendee',
            name='unique_fieldtrip_attendee',
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='6ivenL2aA5Enjwh93hD32K', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
        migrations.AddConstraint(
            model_name='fieldtripattendee',
            constraint=models.UniqueConstraint(fields=('user', 'fieldtrip'), name='unique_fieldtrip_attendee'),
        ),
    ]
