# Generated by Django 5.2 on 2025-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_fieldtrip_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='J27BsTBC8Zb8fLCvvNz5xv', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
