# Generated by Django 5.2 on 2025-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_fieldtrip_invitation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtrip',
            name='link',
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default='PXZ8FSeL8GMJXdZ4XMxoR6', max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
