# Generated by Django 5.2 on 2025-04-15 08:20

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_fieldtrip_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='invitation_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True, verbose_name='Código de invitación a la salida a campo'),
        ),
    ]
