# Generated by Django 5.2 on 2026-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin'), ('auxiliar', 'Auxiliar'), ('inventory_manager', 'Inventory Manager')], max_length=20, verbose_name='Role'),
        ),
    ]
