# Generated by Django 5.2 on 2025-04-14 11:15

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(max_length=30, null=True, verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_number',
            field=models.IntegerField(null=True, validators=[apps.user.models.User.validate_emergency_number], verbose_name='Número de emergencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_previous_experience',
            field=models.BooleanField(default=True, verbose_name='¿Tiene experiencia previa en salidas a campo?'),
        ),
    ]
