# Generated by Django 5.2 on 2025-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet_info',
            field=models.CharField(blank=True, default='', help_text='Ejemplo: "No como azúcar"', max_length=100, verbose_name='Información extra de alimentación'),
        ),
    ]
